### ISSUE TITLE
event formatting issue

### ISSUE THREAD

**Issue by Aikagi000** [eouia/MMM-CalendarExtTimeline#1]
Ok this one I need help on. I really want this to work because there is no other module that does this.

For some reason if I have multiple events in a day on one calendar, it puts each event on a separate line even if the events don't conflict with each other. Also the calendar line doesn't expand to accommodate the events regardless of how many lines they take up. 

Any help is appreciated.

**Comment by eouia** [comment]
can you give the ical url or file for test?

**Comment by Aikagi000** [comment]
Thanks for the fast reply! Here is the ical. The config is the same as you
have on the module site and I've made no css changes.

https://calendar.google.com/calendar/ical/tjj7g69cgog98ugcfshfevdpak%40group.calendar.google.com/private-0c90b09b70450966e11c100c002c5833/basic.ics

**Comment by eouia** [comment]
and one more thing, what feeder module are you using? CalendarExt? CalendarExt2?

**Comment by eouia** [comment]
<img width="800" alt="test" src="https://user-images.githubusercontent.com/1720610/60322562-134a2280-9980-11e9-9b5f-4d5636542674.png">
Hmmm.. with my test, it looks normal. Isn't it your intent?

**Comment by Aikagi000** [comment]
I'm using CalendarExt2. What you show is still not correct:
1 - The workhrs on the second line should be at the end.
2 - It's very strange that you're getting incorrect times from a google
calendar feed =o

weekday sleep 12-7:30am
workhrs 9am-5pm
workhrs 6pm-8pm

3 - the line seems to expand to accommodate the events on yours which is
what I want, but doesn't do that on mine. Any ideas? is it because I'm
using Ext2?

[image: 20190628_094746.jpg]


Here is my config, and the css is attached:

{
 module:"MMM-CalendarExtTimeline",
 position:"bottom_bar",
 config: {
   type: "static", // "static", "dynamic"
   refresh_interval_sec: 60, // minimum 60,
   table_title_format: "ddd, MMM Do",
   begin_hour: 0, //ignored when you set type to 'dynamic'
   end_hour: 24, //how many hours to show.
   time_display_section_count: 12,
   time_display_section_format: "h:mm A",
   calendars: ["Time","Appointments","Events"], //in your `MMM-CalendarExt`
configuration
   source: "CALEXT2", // or "CALEXT"
 }
},

**Comment by eouia** [comment]
![ttt](https://user-images.githubusercontent.com/1720610/60372672-b3925c80-99fd-11e9-96ba-3208ff10f2eb.png)
I tried your config with CALEXT2.
Is this your intent?

(The time of event might be different because we live in different timezone. Just see the duration and the gap of each events)

**Comment by Aikagi000** [comment]
Ok yes that looks right. (and ok with the hrs hadn't thought about time
zone). So what is your setup doing that mine isn't? This is a fresh install
not even a week old for both modules.

**Comment by eouia** [comment]
Nothing special, I used your configuration. no CSS modification for Timeline.
If you have a trouble to post your image, send me via email (eouia0819@gmail.com)

**Comment by Aikagi000** [comment]
Ok so I found out part of the problem,

If the timeline comes *before* the calendar in the config it will put
things on separate lines. If it comes *after* the calendar in the config
..... it puts EVERYTHING on one line lol.

Also ..... if you have "position:relative" in the css class for your custom
calendar event, it messes up the timeline. I don't mind removing that line
but it's worth noting.

Can you see if the same calendar is showing correctly on your end? there
are two evens that should now conflict.

thanks!

**Comment by Aikagi000** [comment]
ok I found something interesting.

If the timeline comes before the calendar in the config it puts each thing
on a separate line.  BUT ....if the timeline comes after the calendar in
the config... it puts *everything* in one line.

Also if you have " position:relative " in the calendar css for a custom
event class, it will make the calendar separate event  onto diff lines also.

I completely commented out my custom css and the time line is still
affected just by it's position.

I'll send images in a separate email to you.

**Comment by eouia** [comment]
I've patched. update or reinstall then try again.

**Comment by Aikagi000** [comment]
OK reinstalled it. 90% or 100% fixed depending on the config position lol:

If the timeline config is ABOVE the calendar config it will look fixed on start up. But when the calendar updates, it breaks.

If the timeline config is BELOW the calendar config it works perfectly!

SO I'm fine with the second option! =D Thank you! I'll let you know if anything else pops up.
---------------------------
User Note: If an event ends at say 1pm, and another event starts at 1pm they will end up on different lines. Two events can't share the same end and start time. Keep that in mind for your google calendar cause google allows it.

**Comment by Aikagi000** [comment]
oops sorry about the bold... I'm new to this site =O
