### ISSUE TITLE
Is it possible to display more than 2 activities per day?

### ISSUE THREAD

**Issue by Doudy** [eouia/MMM-CalendarExtTimeline#3]
Hello,

Is it possible to display more than 2 activities per day?
I have a '+1' which is displayed on 04/19 because I have 3 activities!

![CaptureMMM-timeline](https://user-images.githubusercontent.com/28684288/79306666-f0303580-7ef5-11ea-926b-e5f816c1fa5b.PNG)

**Comment by eouia** [comment]
First, that is not related to this module `MMM-CalendarExtTimeline`. It seems `MMM-CalendarExt2`
Second. You can adjust the height to display more events by `slotMaxHeight`. 
However, you might set height for 3 events. But for 4 events? 5 events? Anyway, it could be an unsolvable problem at the final.

**Comment by Doudy** [comment]
OK thanks

**Comment by Doudy** [comment]
Hello,
I'm back.
Always a worry.
I want to increase the number of displays
No matter how I modify slotMaxHeight nothing 
I tried 
in week : slotMaxHeight: "240px",
in month : slotMaxHeight:"150px",
in locale : slotMaxHeight: "150px",

What value to use?
Does slotCount: 3 have anything to do with the number of displays?
![Capture](https://user-images.githubusercontent.com/28684288/86142332-5e4ac880-baf3-11ea-9001-db453910a15d.PNG)
