### ISSUE TITLE
color the daily activity boxes differently

### ISSUE THREAD

**Issue by Doudy** [eouia/MMM-CalendarExtTimeline#4]
Hello,
I installed MMM-CalendarExtTimeline in addition to MMM-CalendarExt2.
Is it possible to color the daily activity boxes differently.
For example :
Anniversary
Public holiday
Task to perform
Appointment
My Module config:
`{
	module:"MMM-CalendarExtTimeline",
	position:"bottom_bar",
	config: {
	  type: "static", // "static", "dynamic"
	  refresh_interval_sec: 60, // minimum 60,
	  table_title_format: "ddd, Do MMM",
	  begin_hour: 7, //ignored when you set type to 'dynamic'
	  end_hour: 21, //how many hours to show.
	  time_display_section_count: 14,
	  time_display_section_format: "HH:mm",
	  calendars: ["Calendrier"], //in your `MMM-CalendarExt` configuration
	  source: "CALEXT2", // or "CALEXT"
	}
  },
`
Here is what I currently have:
![Capture-MMM-timeline](https://user-images.githubusercontent.com/28684288/80300231-247bdf80-879b-11ea-987f-5746840af0fc.PNG)

Thanks

**Comment by eouia** [comment]
Ask:
- Are the all events in one calendar?
- How can you recognize each category of events? by event title? Is there a rule or condition?

**Comment by Doudy** [comment]
Yes, it is the same calendar.

For a Birthday, there is the term "Anniversaire"
For Holliday, the are the term "Belqique"
For appointment there is a time slot with term "Docteur - Dentiste - etc..."
For task het is a full day appointment

**Comment by eouia** [comment]
I'm somewhat confusing which class you want to change of CalendarExtTimeline or CalenarExt2.
Anyway,
You can assign specific custom CSS classes by "transform".
https://github.com/eouia/MMM-CalendarExt2/wiki/Filtering-and-Sorting

**Comment by Doudy** [comment]
I look at this.
Thank you

**Comment by Doudy** [comment]
Hello,

In the wiki you say " Sorry for all non-developers. But it's not so difficult. The basic concept is here."

Indeed it is not obvious.
I guess I have to use "`transform: (event) => {`"

For example :
[transform: (event)=>{
  if (event.title.search("Anniversaire") > -1) { 
    background-color:rgba(250, 11, 11, 0.6)
  }
  return event 
}
](url)
Is it correct ?
Where should I place this?

**Comment by eouia** [comment]
controllable values of event-object are here; In this case, you can assign new CSS class to that event.
https://github.com/eouia/MMM-CalendarExt2/wiki/Event-Object

```js
transform: (event)=>{
  if (event.title.search("Anniversaire") > -1) {
    event.className = "anniversary"
  }
  return event
}
```

Then, you need to define custom CSS for that class name in `css/custom.css`;
https://github.com/eouia/MMM-CalendarExt2/wiki/4.-Styling

```css
.CX2 .anniversary.fullday {
  background-color:rgba(250, 11, 11, 0.6)
}
```

**Comment by Doudy** [comment]
I try this as soon as possible
Thank you

**Comment by Doudy** [comment]
Hello,
Me again
I added to custom.css :
```
.CX2 .anniversary.fullday {
  background-color:rgba(250, 11, 11, 0.6)
}
```
But where to put following in MMM-CalendarExt2 :
```
transform: (event)=>{
      if (event.title.search("Anniversaire") > -1) {
        event.className = "anniversary"
      }
      return event
    },
```

**Comment by Doudy** [comment]
Hello,
I found the place to put 'transform': MagicMirror\modules\MMM-CalendarExt2\MMM-CalendarExt2.js

If i use the provided script:
`transform: (event) => {return event},`
```
view: {
      mode: "daily",
      className: "",
      position: "top_left",
      positionOrder: -1,
      title: "", //???
      calendars: [],
      filter: (event) => {return true},
      sort: (a,b) => {return a.startDate - b.startDate},
      transform: (event) => {return event},
      locale: "",
      fromNow: 0,
      slotCount: 3,
      slotMaxHeight: "150px",
      hideOverflow: true,
      slotTitleFormat: "",
      slotSubTitleFormat: "",
      slotTitle: "",
      slotSubTitle: "",
      filterPassedEvent: false,
      maxItems:1000,
```
I have following:
![Capture-MMM](https://user-images.githubusercontent.com/28684288/80459546-cc77e100-8932-11ea-9953-a7dba92da2a8.PNG)

When I replace 
`transform: (event) => {return event},`
with:
```
      transform: (event)=>{
        if (event.title.search("Anniversaire") > -1) {
          event.className = "anniversary"
        }
        return event
      },

```
```
    view: {
      mode: "daily",
      className: "",
      position: "top_left",
      positionOrder: -1,
      title: "", //???
      calendars: [],
      filter: (event) => {return true},
      sort: (a,b) => {return a.startDate - b.startDate},
      //transform: (event) => {return event},
      transform: (event)=>{
        if (event.title.search("Anniversaire") > -1) {
          event.className = "anniversary"
        }
        return event
      },
      locale: "",
      fromNow: 0,
      slotCount: 3,
      slotMaxHeight: "150px",
      hideOverflow: true,
      slotTitleFormat: "",
      slotSubTitleFormat: "",
      slotTitle: "",
      slotSubTitle: "",
      filterPassedEvent: false,
      maxItems:1000,
```
 I have following:
![Capture-MMM](https://user-images.githubusercontent.com/28684288/80460342-faa9f080-8933-11ea-9899-950ce8e28ec0.PNG)


But no error !
What does it mean ?

**Comment by eouia** [comment]
first, you don't need to describe all the fields. Most of all are default values already. Just describe what you need to change.
It means you don't need to describe `filter` or `sort`, `locale`, `fromNow`, ... and many things unless you need to specify your own custom values.

**Comment by Doudy** [comment]
I modified according to your advice:
```
view: {
      mode: "daily",
      className: "",
      position: "top_left",
      positionOrder: -1,
      title: "", //???
      calendars: [],

      transform: (event) => {
        if (event.title.search("Anniversaire") > -1) {
          event.className = "anniversary"
        }
        return event
      },
     ....
```
But the result is always the same.
No day display ...
![Capture-MMM](https://user-images.githubusercontent.com/28684288/80460342-faa9f080-8933-11ea-9899-950ce8e28ec0.PNG)

**Comment by eouia** [comment]
Give me your real ical url and whole configuration (eouia0819@gmail.com)

**Comment by Doudy** [comment]
E-mail sent

**Comment by eouia** [comment]
Not yet received.

**Comment by Doudy** [comment]
E-mail returned

**Comment by Doudy** [comment]
Did you receive my email ?

**Comment by Doudy** [comment]
It works now.
Thank you

```
transform: (event) => {
        if (event.title.search("Anniversaire") > -1) {
          event.className = "anniversary"
        } else if (event.title.search("Papiers") > -1) {
          event.className = "garbage"
          event.icon = "mdi:recycle"
        }
        return event
      },
```
