### ISSUE TITLE
VIEW and COLORS

### ISSUE THREAD

**Issue by thetobyde** [eouia/MMM-CalendarExtTimeline#7]
Hey mate :) 2 Questions:
How can I get colors in the module like u have?
and how can I get these Mon, Tue, Wed ... format like the bottom of your screenshot?
Thank U for help! :)
Toby

**Comment by wegunterjr** [comment]
did you ever find the answer? 
Was it just taking what was in the css and adding it to the custom.css and changing the colors to match?
